name = "family-wallet-api"
main = "dist/server-cloudflare.js"
compatibility_date = "2024-10-01"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

[vars]
ENVIRONMENT = "production"
USE_MOCK_DATA = "false"

# Environment variables (set via wrangler secret put)
# Required secrets:
# - DATABASE_URL (Neon PostgreSQL connection string)
# - JWT_SECRET (for authentication)
# - WEB_ORIGIN (CORS allowed origin)

# Development configuration
[env.dev]
name = "family-wallet-api-dev"
vars = { ENVIRONMENT = "development", USE_MOCK_DATA = "true" }

[env.dev.dev]
port = 3001
